steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
      #            '-t', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${BRANCH_NAME}',
            '-t', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:latest',
            '.' ]
  - name: "gcr.io/cloud-builders/gke-deploy"
    args: [ 'run',
            '--filename=pod.yaml',
            '--location=asia-southeast1',
            '--cluster=autopilot-cluster-1' ]
options:
  logging: CLOUD_LOGGING_ONLY