steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${BRANCH_NAME}', '.' ]
    substitutions:
      _LOCATION: asia-southeast1
      _PROJECT_ID: poc-testing-personal
      _REPOSITORY: personal-docker
      _IMAGE: web-stg
images:
  - '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_IMAGE}'
