apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
spec:
  containers:
    - name: web
      image: asia-southeast1-docker.pkg.dev/poc-testing-personal/personal-docker/web-stg:latest
      ports:
        - containerPort: 8080

